export const FontFamily = Object.freeze({
  // black: 'Urbanist-Black',
  // blackItalic: 'Urbanist-BlackItalic',
  bold: 'Urbanist-Bold',
  // boldItalic: 'Urbanist-BoldItalic',
  // extraBold: 'Urbanist-ExtraBold',
  // extraBoldItalic: 'Urbanist-ExtraBoldItalic',
  // extraLight: 'Urbanist-ExtraLight',
  // extraLightItalic: 'Urbanist-ExtraLightItalic',
  // italic: 'Urbanist-Italic',
  // light: 'Urbanist-Light',
  // lightItalic: 'Urbanist-LightItalic',
  medium: 'Urbanist-Medium',
  // mediumItalic: 'Urbanist-MediumItalic',
  regular: 'Urbanist-Regular',
  semiBold: 'Urbanist-SemiBold',
  // semiBoldItalic: 'Urbanist-SemiBoldItalic',
  // thin: 'Urbanist-Thin',
  // thinItalic: 'Urbanist-ThinItalic',
});
