export const Icons = Object.freeze({
  arrowLeft: require('./arrowLeft.png'),
  eye: require('./eye.png'),
  eye_close: require('./eye_close.png'),
  correct: require('./correct.png'),
  tabSelectedDashboard: require('./tabSelectedDashboard.png'),
  tabSelectedScan: require('./tabSelectedScan.png'),
  tabSelectedSettings: require('./tabSelectedSettings.png'),
  dashboard: require('./dashboard.png'),
  scan: require('./scan.png'),
  settings: require('./settings.png'),
  premium: require('./premium.png'),
  refresh: require('./refresh.png'),
  edit: require('./edit.png'),
  delete: require('./delete.png'),
  add: require('./add.png'),
  close: require('./close.png'),
  warning: require('./warning.png'),
  rightArrow: require('./rightArrow.png'),
  flashOn: require('./flashOn.png'),
});
